# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96c7b98a973be3eabf9cf6de8ffdc31f53769ddadbe19b63a0ca4f374bcd063639a3fc3c5cab85f7f6e003d9b9e8ef4c07817e0d574bb3d0340aae2437fe5092

test:
  secret_key_base: 0bcdf28f56c7b926938276bfe46a7747488048abd66dcb66eb72098d7e08ff31fcade904aed29c163a3845192c55a8c265094ef9a6ffc6ace82ac5a1f4f93115

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
